### ISSUE TITLE
Support C++17 (or lower)?

### ISSUE THREAD

**Issue by lei-april** [bytecodealliance/wasmtime-cpp#3]
Hi,

First of all, thank you for your wonderful job. I'm embedding wasmtime into a C++ project, and the C++ API is much nicer to work with than the original C API.

But there's one thing that troubles me a bit. Compiler support for C++20 is far from mature, and upgrading the C++ standard used by a big C++ project (like mine) is not a trivial job :(

So would you consider lowering the C++ standard required? I think it could be easier for existing C++ projects to embed this wrapper.

Thanks

**Comment by alexcrichton** [comment]
Seems reasonable to me to support! The only reason I ended up enabling C++20 was for the `std::span` type. Do you know if there's an alternate type for a similar purpose pre-C++20? The main place this matters I think is return values because presumably functions that use it as an argument could just have an overload with a pointer/length. In the few places it's a return value there could perhaps be two functions returning pointer/length?

**Comment by lei-april** [comment]
I too think `std::span` is a very convenient type. Unfortunately there's no alternative to it (to my knowledge) in the pre-C++20 standard library.

Microsoft's [GSL](https://github.com/microsoft/GSL) has an implementation of `span` very similar to C++20's, and it only requires C++14. Other than that, maybe you could rollout a homebrew `span` 😉

**Comment by redradist** [comment]
@lei-april 
> 
> 
> I too think `std::span` is a very convenient type. Unfortunately there's no alternative to it (to my knowledge) in the pre-C++20 standard library.
> 
> Microsoft's [GSL](https://github.com/microsoft/GSL) has an implementation of `span` very similar to C++20's, and it only requires C++14. Other than that, maybe you could rollout a homebrew `span` 😉

Completely agree, I use `gsl::span` whenever possible

**Comment by redradist** [comment]
Here is PR for switching to C++17 https://github.com/bytecodealliance/wasmtime-cpp/pull/5

**Comment by alexcrichton** [comment]
Fixed in https://github.com/bytecodealliance/wasmtime-cpp/pull/5, thanks again @redradist!
